import "server-only";
import { and, asc, desc, eq } from "drizzle-orm";
import { withRlsContext } from "@/db/client";
import { conversationMessages, leadScores, leads, type Lead } from "@/db/schema";
import { requireCompanySession } from "@/lib/auth/session";
import { assertPermission } from "@/modules/permissions";
import { recordAuditLog } from "@/modules/audit/service";
import { getAiProvider } from "@/providers/ai";
import { loadAiBehaviourForConversation } from "@/modules/ai-behaviour/conversation-config";
import { recordActivity } from "./activity";
import { assertLeadBelongsToOrg } from "./shared";
import { computeLeadScore, type LeadScoreSignals } from "./scoring";

/**
 * Structured, not free-form text (module spec §3: "Store structured JSON.
 * Not free-form text only"). Generated by prompting the org's own
 * configured provider (providers/ai, reused as-is — no new AI-calling code
 * path) to analyze the lead's conversation and return exactly this shape.
 */
export type LeadAiSummary = {
  whoIsThisPerson: string;
  whatDoTheyNeed: string;
  budget: string | null;
  timeline: string | null;
  painPoints: string[];
  productsDiscussed: string[];
  recommendedNextAction: string;
  intentScore: number;
  urgencyScore: number;
  buyingSignalsScore: number;
  supportSignalsScore: number;
  budgetMentioned: boolean;
  generatedAt: string;
};

// Only the fields this module reads from the provider's JSON response —
// everything else is defensively coerced/defaulted below, never trusted
// as-is (an LLM response is untrusted input, same as any other boundary).
type RawSummaryResponse = {
  whoIsThisPerson?: unknown;
  whatDoTheyNeed?: unknown;
  budget?: unknown;
  timeline?: unknown;
  painPoints?: unknown;
  productsDiscussed?: unknown;
  recommendedNextAction?: unknown;
  intentScore?: unknown;
  urgencyScore?: unknown;
  buyingSignalsScore?: unknown;
  supportSignalsScore?: unknown;
  budgetMentioned?: unknown;
};

const SUMMARY_SYSTEM_PROMPT = `You analyze a sales conversation and extract structured information about the lead. Respond with ONLY a single JSON object, no other text, no markdown code fences, matching exactly this shape:
{
  "whoIsThisPerson": string,
  "whatDoTheyNeed": string,
  "budget": string or null,
  "timeline": string or null,
  "painPoints": string[],
  "productsDiscussed": string[],
  "recommendedNextAction": string,
  "intentScore": number from 0 to 10 (how likely they are to buy),
  "urgencyScore": number from 0 to 10 (how time-sensitive their need is),
  "buyingSignalsScore": number from 0 to 10 (explicit buying signals present),
  "supportSignalsScore": number from 0 to 10 (how much this looks like a support request rather than a sales opportunity),
  "budgetMentioned": boolean
}
Only use information actually present in the conversation. If something isn't mentioned, use null, an empty array, or 0 — never invent details.`;

function extractJsonObject(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced ? fenced[1] : text;
  const start = candidate.indexOf("{");
  const end = candidate.lastIndexOf("}");
  if (start === -1 || end === -1 || end < start) return candidate;
  return candidate.slice(start, end + 1);
}

function clampScore(value: unknown): number {
  const num = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(num)) return 0;
  return Math.max(0, Math.min(10, num));
}

function toStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.map((v) => String(v)) : [];
}

/**
 * Fetches the lead's conversation, asks the org's configured AI provider
 * to analyze it, stores the structured result plus a recomputed score
 * (module spec §3/§4). Fully buffered (not streamed to a client) — reuses
 * the exact same AsyncGenerator<AiStreamEvent> providers/ai contract the
 * Conversation Engine uses, just consumed differently.
 */
export async function generateLeadSummary(leadId: string): Promise<Lead> {
  const session = await requireCompanySession();
  assertPermission(session, "leads.update");

  const { lead, messages } = await withRlsContext(session.userId, async (tx) => {
    await assertLeadBelongsToOrg(tx, leadId, session);
    const [leadRow] = await tx.select().from(leads).where(eq(leads.id, leadId)).limit(1);

    const messageRows = leadRow.conversationId
      ? await tx
          .select()
          .from(conversationMessages)
          .where(eq(conversationMessages.conversationId, leadRow.conversationId))
          .orderBy(asc(conversationMessages.createdAt))
      : [];

    return { lead: leadRow, messages: messageRows };
  });

  const transcriptMessages = messages.filter((m) => m.role === "user" || m.role === "assistant");
  if (transcriptMessages.length === 0) {
    throw new Error("This lead has no conversation to summarize");
  }

  const behaviourConfig = await loadAiBehaviourForConversation(session.organizationId);
  const provider = getAiProvider(behaviourConfig.profile.aiProvider);
  const transcript = transcriptMessages.map((m) => `${m.role}: ${m.content}`).join("\n");

  let accumulated = "";
  for await (const event of provider.streamChat({
    systemPrompt: SUMMARY_SYSTEM_PROMPT,
    messages: [{ role: "user", content: transcript }],
  })) {
    if (event.type === "token") {
      accumulated += event.text;
    } else if (event.type === "error") {
      throw new Error(`Summary generation failed: ${event.message}`);
    }
  }

  let raw: RawSummaryResponse;
  try {
    raw = JSON.parse(extractJsonObject(accumulated)) as RawSummaryResponse;
  } catch {
    throw new Error("The AI provider did not return valid structured JSON for this summary.");
  }

  const summary: LeadAiSummary = {
    whoIsThisPerson: typeof raw.whoIsThisPerson === "string" ? raw.whoIsThisPerson : "",
    whatDoTheyNeed: typeof raw.whatDoTheyNeed === "string" ? raw.whatDoTheyNeed : "",
    budget: typeof raw.budget === "string" ? raw.budget : null,
    timeline: typeof raw.timeline === "string" ? raw.timeline : null,
    painPoints: toStringArray(raw.painPoints),
    productsDiscussed: toStringArray(raw.productsDiscussed),
    recommendedNextAction: typeof raw.recommendedNextAction === "string" ? raw.recommendedNextAction : "",
    intentScore: clampScore(raw.intentScore),
    urgencyScore: clampScore(raw.urgencyScore),
    buyingSignalsScore: clampScore(raw.buyingSignalsScore),
    supportSignalsScore: clampScore(raw.supportSignalsScore),
    budgetMentioned: Boolean(raw.budgetMentioned),
    generatedAt: new Date().toISOString(),
  };

  const updated = await withRlsContext(session.userId, async (tx) => {
    // Preserve any prior manual score adjustment rather than silently
    // discarding it on regeneration — a human's explicit override should
    // survive an AI re-summary.
    const [latestScore] = await tx
      .select({ signals: leadScores.signals })
      .from(leadScores)
      .where(and(eq(leadScores.leadId, leadId), eq(leadScores.organizationId, session.organizationId)))
      .orderBy(desc(leadScores.createdAt))
      .limit(1);
    const priorManualAdjustment = (latestScore?.signals as LeadScoreSignals | undefined)?.manualAdjustment ?? 0;

    const signals: LeadScoreSignals = {
      emailCaptured: Boolean(lead.email),
      phoneCaptured: Boolean(lead.phone),
      companyCaptured: Boolean(lead.company),
      messageCount: transcriptMessages.length,
      budgetMentioned: summary.budgetMentioned,
      intentScore: summary.intentScore,
      urgencyScore: summary.urgencyScore,
      buyingSignalsScore: summary.buyingSignalsScore,
      supportSignalsScore: summary.supportSignalsScore,
      manualAdjustment: priorManualAdjustment,
    };
    const totalScore = computeLeadScore(signals);

    const [row] = await tx
      .update(leads)
      .set({ aiSummary: summary, score: totalScore, updatedAt: new Date() })
      .where(eq(leads.id, leadId))
      .returning();

    await tx.insert(leadScores).values({ organizationId: session.organizationId, leadId, signals, totalScore });
    await recordActivity(tx, {
      organizationId: session.organizationId,
      leadId,
      type: "summary_generated",
      actorUserId: session.userId,
      metadata: { totalScore },
    });

    return row;
  });

  // Never the summary content itself in audit metadata — it can contain
  // sensitive prospect information (CLAUDE.md §6).
  await recordAuditLog({
    organizationId: session.organizationId,
    actorUserId: session.userId,
    actorType: "company_user",
    action: "leads.summary_generated",
    resourceType: "lead",
    resourceId: leadId,
    metadata: { score: updated.score },
  });

  return updated;
}
