export const PERMISSIONS = [
  "company.view",
  "company.manage",
  "users.view",
  "users.manage",
  "leads.view",
  "leads.create",
  "leads.update",
  "leads.delete",
  "leads.assign",
  "conversations.view",
  "inbox.view",
  "inbox.reply",
  "knowledge.view",
  "knowledge.create",
  "knowledge.update",
  "knowledge.delete",
  "knowledge.search",
  "knowledge.reprocess",
  "ai.view",
  "ai.update",
  "ai.test",
  "widget.view",
  "widget.create",
  "widget.update",
  "widget.delete",
  "widget.publish",
  "analytics.view",
  "analytics.export",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
